services:
  db:
    image: postgres:14
    container_name: ai-car
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  redis:
    image: redis:7-alpine
    container_name: ai-car-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    restart: always
